<a href="https://colab.research.google.com/github/sandranh/Data-Science-portfolio/blob/main/Data_Collection_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Collecting data from an API

In [1]:
import requests
import pandas as pd

In [6]:
country = "ZAF"
indicators = {
    "GDP_USD": "NY.GDP.MKTP.CD",
    "Inflation": "FP.CPI.TOTL.ZG"
}
dfs=[]
for name, indicator in indicators.items():
  url = f"https://api.worldbank.org/v2/country/{country}/indicator/{indicator}"
  params ={
      "format": "json",
      "per_page":100

  }
  response = requests.get(url, params=params)
  data = response.json()[1]
  df= pd.DataFrame(data)[["date","value"]]
  df.columns =["Year",name]
  dfs.append(df)

In [7]:
# Merge GDP and Inflation on year
result = dfs[0].merge(dfs[1], on="Year")

# Sort chronologically
result["Year"] = result["Year"].astype(int)
result = result.sort_values("Year")

result.head()

    Year       GDP_USD  Inflation
65  1960  8.748597e+09   1.288877
64  1961  9.225996e+09   2.102351
63  1962  9.813996e+09   1.246275
62  1963  1.085420e+10   1.337971
61  1964  1.195600e+10   2.534989

In [8]:
#Collecting data using web scraping
!pip install beautifulsoup4
from bs4 import BeautifulSoup

Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.16.0)

In [27]:
page_to_scrape = requests.get("http://quotes.toscrape.com")
soup = BeautifulSoup(page_to_scrape.text, "html.parser")
quotes = soup.find_all("span", attrs={"class":"text"})
authors = soup.find_all("small", attrs={"class":"author"})
for quote, author in zip (quotes, authors):
  print(quote.text + "-" + author.text)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”-Albert Einstein
“It is our choices, Harry, that show what we truly are, far more than our abilities.”-J.K. Rowling
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”-Albert Einstein
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”-Jane Austen
“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”-Marilyn Monroe
“Try not to become a man of success. Rather become a man of value.”-Albert Einstein
“It is better to be hated for what you are than to be loved for what you are not.”-André Gide
“I have not failed. I've just found 10,000 ways that won't work.”-Thomas A. Edison
“A woman is like a tea bag; you never know how strong it is until it's in hot water.”-Eleanor Roosevelt
“A day without sunshine is like, you know, night.”-Steve Martin

In [30]:
quotes_list= []
for quotes, author in zip (quotes, authors):
 quotes_list.append({
        "Quote": quote.text.strip(),
        "Author": author.text.strip()
    })
df_quotes = pd.DataFrame(quotes_list)
print ("Successfully loaded into pandas dataframe")
print(df_quotes.head())

Successfully loaded into pandas dataframe
                                               Quote           Author
0  “A day without sunshine is like, you know, nig...  Albert Einstein
1  “A day without sunshine is like, you know, nig...     J.K. Rowling
2  “A day without sunshine is like, you know, nig...  Albert Einstein
3  “A day without sunshine is like, you know, nig...      Jane Austen
4  “A day without sunshine is like, you know, nig...   Marilyn Monroe

In [33]:
#Collecting data from the cloud
regions_and_populations = "https://raw.githubusercontent.com/datasets/gdp/master/data/gdp.csv"
df = pd.read_csv(regions_and_populations)
df.head()

  Country Name Country Code  Year         Value
0  Afghanistan          AFG  2000  3.521418e+09
1  Afghanistan          AFG  2001  2.813572e+09
2  Afghanistan          AFG  2002  3.825701e+09
3  Afghanistan          AFG  2003  4.520947e+09
4  Afghanistan          AFG  2004  5.224897e+09

In [38]:
df.info()
df.isnull().sum()
south_africa = df[df["Country Name"]== "South Africa"]
south_africa.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13979 entries, 0 to 13978
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  13979 non-null  object
 1   Country Code  13979 non-null  object
 2   Year          13979 non-null  int64
 3   Value         13979 non-null  float64
dtypes: float64(1), int64(1), object(2)
memory usage: 437.0+ KB

       Country Name Country Code  Year         Value
11494  South Africa          ZAF  1960  8.748597e+09
11495  South Africa          ZAF  1961  9.225996e+09
11496  South Africa          ZAF  1962  9.813996e+09
11497  South Africa          ZAF  1963  1.085420e+10
11498  South Africa          ZAF  1964  1.195600e+10